testname: Sprecherherkunft
testId: lss_lms
bufferSize: 2048
stopOnErrors: false
showButtonPreviousPage: true
remoteService: service/write.php
# language: de

pages:
  - type: mushra_de_at
    id: mushra1
    name: MUSHRA
    content: Bitte geben Sie an, aus welcher Region Ihrer Meinung nach die Sprecher*innen stammen.
    showWaveform: false
    enableLooping: false
    hideReference: true
    reference: configs/resources/audio/AT_DE/WS22_AW.wav
    createAnchor35: false
    createAnchor70: false
    randomize: true
    showConditionNames: false
    stimuli:
      C1: configs/resources/audio/AT_DE/WS28_MZ-AW-VE_0.4_0.6_0.0.wav
      # C2: configs/resources/audio/AT_DE/WS21_MZ-AW-VE_0.4_0.6_0.0.wav
      # C3: configs/resources/audio/AT_DE/WS20_MZ-AW-VE_0.5_0.5_0.0.wav
      # C4: configs/resources/audio/AT_DE/WS28_MZ.wav
      # C5: configs/resources/audio/AT_DE/WS5_MZ-AW-VE_0.5_0.5_0.0.wav
      # C6: configs/resources/audio/AT_DE/WS28_MZ-AW-VE_0.2_0.8_0.0.wav
      # C7: configs/resources/audio/AT_DE/WS22_MZ-AW-VE_0.4_0.6_0.0.wav
      # C8: configs/resources/audio/AT_DE/WS5_AW.wav
      # C9: configs/resources/audio/AT_DE/WS22_MZ.wav  # VE sollte nicht hier sein

  # - type: mushra_de_ch
  #   id: mushra2
  #   name: MUSHRA
  #   content: Bitte geben Sie an, aus welcher Region Ihrer Meinung nach die Sprecher*innen stammen.
  #   showWaveform: true
  #   enableLooping: false
  #   reference: configs/resources/audio/mono_ref.wav
  #   createAnchor35: false
  #   createAnchor70: false
  #   randomize: true
  #   showConditionNames: false
  #   stimuli:
  #     C1: configs/resources/audio/mono_c1.wav
  #     C2: configs/resources/audio/mono_c2.wav
  #     C3: configs/resources/audio/mono_c3.wav
  #     C4: configs/resources/audio/mono_c1.wav
  #     C5: configs/resources/audio/mono_c2.wav
  #     C6: configs/resources/audio/mono_c3.wav
  #     C7: configs/resources/audio/mono_c1.wav
  #     C8: configs/resources/audio/mono_c2.wav
  #     C9: configs/resources/audio/mono_c3.wav
  #     C10: configs/resources/audio/mono_c1.wav
  #     C11: configs/resources/audio/mono_c2.wav

  - type: generic
    id: LSS_LMS
    name: Einführung
    content: <ul> <li>Bitte geben Sie an, aus welcher Region Ihrer Meinung nach die Sprecher*innen stammen</li>
  - type: likert_multi_stimulus
    id: lms2
    name: Sprachbeispiele
    content: Die Person kommt aus?
    stimuli:
        C1: configs/resources/audio/AT_DE/WS5_MZ-AW-VE_0.2_0.8_0.0.wav
        C2: configs/resources/audio/AT_DE/WS20_MZ-AW-VE_0.4_0.6_0.0.wav
        C3: configs/resources/audio/AT_DE/WS21_MZ-AW-VE_0.5_0.5_0.0.wav
        C4: configs/resources/audio/AT_DE/WS22_MZ-AW-VE_0.6_0.4_0.0.wav
        C5: configs/resources/audio/AT_DE/WS28_MZ-AW-VE_0.8_0.2_0.0.wav

    # response:
    #   - value: Österreich
    #     label: "    Österreich"
    #     img: configs/resources/images/star_off.png
    #     imgSelected: configs/resources/images/star_on.png
    #     imgHigherResponseSelected: configs/resources/images/star_on.png
    #   - value: eher Österreich
    #     label: eher Österreich
    #     img: configs/resources/images/star_off.png
    #     imgSelected: configs/resources/images/star_on.png
    #     imgHigherResponseSelected: configs/resources/images/star_on.png
    #   - value: unentschieden
    #     label: unentschieden
    #     img: configs/resources/images/star_off.png
    #     imgSelected: configs/resources/images/star_on.png
    #     imgHigherResponseSelected: configs/resources/images/star_on.png
    #   - value: eher Deutschland
    #     label: eher Deutschland
    #     img: configs/resources/images/star_off.png
    #     imgSelected: configs/resources/images/star_on.png
    #     imgHigherResponseSelected: configs/resources/images/star_on.png
    #   - value: Deutschland
    #     label: Deutschland
    #     img: configs/resources/images/star_off.png
    #     imgSelected: configs/resources/images/star_on.png
    #     imgHigherResponseSelected: configs/resources/images/star_on.png
  - type: spatial
    id : test_page
    name: localization of a stimulus
    content: <li>Woher SSSstammen die Sprecher*innen? </li> <li> Klicken Sie zuerst auf den Button, dann innerhalb, bzw entlang den Linien des Dreiecks um die Kugel zu versetzen. Wenn Sie nur eine Mischung von zwei Herkünften hören, setzen Sie den Punkt dementsprechend auf der Linie zwischen den jeweiligen Eckpunkten.</li><li> Bleiben Sie beim Setzen innerhalb des Dreiecks, bzw auf den Linien.
    framerate: 100
    roomMeasurements: [300, 300, 300]  # width, height, length
    stimuli:
        C1: configs/resources/audio/WS5_MZ-AW-VE_0.25_0.25_0.5.wav
        C2: configs/resources/audio/WS5_MZ-AW-VE_0.25_0.25_0.5.wav
    responses:
      - type: localization2
        name: i_1
        label: HIIEEER klicken, dann Punkt setzen
        color: 0xff5500      
        stimulus: C1    
        position: [0,0,25]
        size: 20
      - type: localization2
        name: i_2
        label: HIIEEER klicken, dann Punkt setzen
        color: 0xff5500      
        stimulus: C2   
        position: [0,0,25]
        size: 20
    views: 
      - view: top
      - view: top
        position: [0,50,0]
    objects: 
      - type: listener
        position: [0,250,-1000]
        rotation: [0,0,180]
  - type: finish
    name: Thank you
    content: Thank you for attending
    showResults: true
    writeResults: true
    questionnaire:
        - type: text
          label: name/shortname/nickname
          name: email